# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1280, 720)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Main)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_left_Layout = QtWidgets.QVBoxLayout()
        self.main_left_Layout.setObjectName("main_left_Layout")
        self.main_left_image_label = QtWidgets.QLabel(Main)
        self.main_left_image_label.setText("")
        self.main_left_image_label.setScaledContents(True)
        self.main_left_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_left_image_label.setObjectName("main_left_image_label")
        self.main_left_Layout.addWidget(self.main_left_image_label)
        self.horizontalLayout.addLayout(self.main_left_Layout)
        self.main_right_Layout = QtWidgets.QVBoxLayout()
        self.main_right_Layout.setObjectName("main_right_Layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.main_right_Layout.addItem(spacerItem)
        self.select_challenge_pushButton = QtWidgets.QPushButton(Main)
        self.select_challenge_pushButton.setObjectName("select_challenge_pushButton")
        self.main_right_Layout.addWidget(self.select_challenge_pushButton)
        self.view_rank_pushButton = QtWidgets.QPushButton(Main)
        self.view_rank_pushButton.setObjectName("view_rank_pushButton")
        self.main_right_Layout.addWidget(self.view_rank_pushButton)
        self.ID_lineEdit = QtWidgets.QLineEdit(Main)
        self.ID_lineEdit.setInputMask("")
        self.ID_lineEdit.setObjectName("ID_lineEdit")
        self.main_right_Layout.addWidget(self.ID_lineEdit)
        self.Name_lineEdit = QtWidgets.QLineEdit(Main)
        self.Name_lineEdit.setObjectName("Name_lineEdit")
        self.main_right_Layout.addWidget(self.Name_lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.main_right_Layout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.main_right_Layout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Main"))
        self.select_challenge_pushButton.setText(_translate("Main", "챌린지 선택"))
        self.view_rank_pushButton.setText(_translate("Main", "랭킹 보기"))
        self.ID_lineEdit.setPlaceholderText(_translate("Main", "아이디를 입력하세요"))
        self.Name_lineEdit.setPlaceholderText(_translate("Main", "이름을 입력하세요"))
