# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rank_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rank_main_verticalLayout = QtWidgets.QVBoxLayout()
        self.rank_main_verticalLayout.setObjectName("rank_main_verticalLayout")
        self.page_title_VL = QtWidgets.QVBoxLayout()
        self.page_title_VL.setObjectName("page_title_VL")
        self.page_title_label = QtWidgets.QLabel(Form)
        self.page_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.page_title_label.setObjectName("page_title_label")
        self.page_title_VL.addWidget(self.page_title_label)
        self.rank_main_verticalLayout.addLayout(self.page_title_VL)
        self.rank_HL = QtWidgets.QHBoxLayout()
        self.rank_HL.setObjectName("rank_HL")
        self.rank_list_VL = QtWidgets.QVBoxLayout()
        self.rank_list_VL.setObjectName("rank_list_VL")
        self.video_list_listWidget = QtWidgets.QListWidget(Form)
        self.video_list_listWidget.setObjectName("video_list_listWidget")
        self.rank_list_VL.addWidget(self.video_list_listWidget)
        self.player_video_listWidget = QtWidgets.QListWidget(Form)
        self.player_video_listWidget.setObjectName("player_video_listWidget")
        self.rank_list_VL.addWidget(self.player_video_listWidget)
        self.rank_HL.addLayout(self.rank_list_VL)
        self.video_play_VL = QtWidgets.QVBoxLayout()
        self.video_play_VL.setObjectName("video_play_VL")
        self.select_video_play_GV = QtWidgets.QGraphicsView(Form)
        self.select_video_play_GV.setObjectName("select_video_play_GV")
        self.video_play_VL.addWidget(self.select_video_play_GV)
        self.rank_HL.addLayout(self.video_play_VL)
        self.rank_main_verticalLayout.addLayout(self.rank_HL)
        self.rank_control_HL = QtWidgets.QHBoxLayout()
        self.rank_control_HL.setObjectName("rank_control_HL")
        self.go_to_main_PB = QtWidgets.QPushButton(Form)
        self.go_to_main_PB.setObjectName("go_to_main_PB")
        self.rank_control_HL.addWidget(self.go_to_main_PB)
        self.rank_main_verticalLayout.addLayout(self.rank_control_HL)
        self.rank_main_verticalLayout.setStretch(0, 1)
        self.rank_main_verticalLayout.setStretch(1, 8)
        self.rank_main_verticalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.rank_main_verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.page_title_label.setText(_translate("Form", "랭킹보기"))
        self.go_to_main_PB.setText(_translate("Form", "메인으로"))
